# -*- coding: utf-8 -*-
"""utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pqv3FuZiVgQDh11p8p5hlci2BgVr5PEn
"""

import os
import joblib
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression

MODEL_DIR = "artifacts"
os.makedirs(MODEL_DIR, exist_ok=True)

def load_data(test_size=0.2, random_state=42):
    X, y = fetch_california_housing(return_X_y=True)
    return train_test_split(X, y, test_size=test_size, random_state=random_state)

def save_model(model, filename="model.joblib"):
    filepath = os.path.join(MODEL_DIR, filename)
    joblib.dump(model, filepath)
    return filepath

def load_model(filename="model.joblib"):
    filepath = os.path.join(MODEL_DIR, filename)
    return joblib.load(filepath)

def evaluate_model(model, X_test, y_test):
    y_pred = model.predict(X_test)
    r2 = r2_score(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    return r2, mse