name: CI Pipeline
'on':
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest tests/
  train-and-quantize:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Utils
        run: python src/utils.py
        working-directory: ${{ github.workspace }}
      - name: Run Training
        run: python src/train.py
        working-directory: ${{ github.workspace }}
      - name: Run Quantization
        run: python src/quantize.py
        working-directory: ${{ github.workspace }}
      - name: Run Prediction
        run: python src/predict.py
        working-directory: ${{ github.workspace }}
  docker-build:
    needs: train-and-quantize
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Docker
        run: docker build -t linear-model .
      - name: Run Docker
        run: docker run --rm linear-model
